name: Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
      upload_artifact:
        description: "Upload Artifact"
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build FFXIVM
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.2.1
        with:
          path: main
          submodules: recursive

      - name: Caching brew dependencies
        id: brew_cache
        uses: tecolicom/actions-use-homebrew-tools@v1.2
        with:
          tools: ldid dpkg make
          cache: yes

      - name: Install Dependencies
        if: steps.brew_cache.outputs.cache-hit != 'true'
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup Theos
        uses: actions/checkout@v4.2.1
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Caching SDK
        id: SDK
        uses: actions/cache@v4
        env:
          cache-name: iOS-16.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 16.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git && cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.2.1
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          mkdir -p theos/lib/iphone/rootless
          cd ${{ github.workspace }}/main
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"

        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: FFXIVM-en-patch
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
